language: python
install: pip install -qr requirements.txt
script: python test_app.py
notifications:
  irc:
    channels:
      - "irc.freenode.net#tsuru"
    on_success: change
    on_failure: always
