language: python
install: cat requirements.apt | xargs sudo apt-get install -qqy
script: make test
services: mongodb
notifications:
  irc:
    channels:
      - "irc.freenode.net#tsuru"
    on_success: change
    on_failure: always
